### ISSUE TITLE
Datasets with multiple owners

### ISSUE THREAD

**Issue by danfowler** [openspending/openspending-migrate#8]
I am inclined to duplicate datasets that have multiple owners, however, [4.4 GB](https://github.com/openspending/openspending-migrate/issues/3) of datasets have 2 owners, meaning that this method would result in at least that much space being occupied by duplicate data.

**Comment by pwalsh** [comment]
@danfowler 

I suggest the following:
- don't duplicate - datasets go to the "first owner"
  - first owner can mean many things. If possible, can you identify which owner uploaded the dataset? If yes, use that. If not, then just take the first owner from the list
- store the additional owners ("additional_owners" property?)
- keep a list for our reference of these datasets, and we'll see how we handle them in future

**Comment by danfowler** [comment]
Done. Just using first owner from list.
